### ISSUE TITLE
What about changing default port numbers?

### ISSUE THREAD

**Issue by agoncal** [appdevgbb/reddog-code-spring#59]
Today the application uses `808x` port range:

| Service              | port |
|----------------------|------|
| Virtual Customer     | 8081 |
| Order Service        |  8082 |
| Loyalty Service      | 8083 |
| Makeline Service     | 8084 |
| Receipt generation   | 8085 |
| Virtual Worker       | 8086 |
| Accounting Service   | 8087 |

The problem is that these ports are quite common and used by other processes. If you look at the [list of common ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), the range `870x` is not used.

What about changing port numbers?

| Service              | port |
|----------------------|------|
| Virtual Customer     | 8701 |
| Order Service        |  8702 |
| Loyalty Service      | 8703 |
| Makeline Service     | 8704 |
| Receipt generation   | 8705 |
| Virtual Worker       | 8706 |
| Accounting Service   | 8707 |

**Comment by thegovind** [comment]
Just getting to this. Yes, will change them to 870x range. Simiraly, if you could update the quarkus one for 880x range (or another less common ones), that would be great. Thanks for the suggestion!
