### ISSUE TITLE
Singular or plural package names?

### ISSUE THREAD

**Issue by agoncal** [appdevgbb/reddog-code-spring#62]
"Naming things is hard"... and naming packages is even harder ;o)

The project uses a mixture of singular and plural for the package names: 

* Singular: `controller`, `dto`, `exception`, `mapper`, `service`
* Plural: `repositories`, `entities`

I wonder if `repositories` and `entities` could be renamed to singular (`repository` and `entity`) for naming convention ?

**Comment by thegovind** [comment]
Good observation. Agree. Will refactor as suggested
